FROM registry.redhat.io/ubi9/nodejs-18:latest AS web-builder

WORKDIR /usr/src/app

RUN npm install --global yarn

COPY web/package.json web/yarn.lock .
RUN yarn

COPY ./web .

ENTRYPOINT ["yarn", "lint"]
