FROM registry.redhat.io/ubi9/nodejs-18:latest AS web-builder

WORKDIR /opt/app-root

USER 0

ENV HUSKY=0
COPY web/package*.json web/
COPY Makefile Makefile
RUN make install-frontend-ci

COPY web/ web/

ENTRYPOINT ["make", "lint-frontend"]