FROM registry.redhat.io/rhel8/nodejs-16:1-105.1684740145

WORKDIR /usr/src/app

RUN npm install --global yarn

COPY web/package.json web/yarn.lock .
RUN yarn

COPY ./web .

ENTRYPOINT ["yarn", "lint"]
